######################################################################
# Automatically generated by qmake (3.0) lun. juin 15 14:34:39 2015
######################################################################

TEMPLATE = app
TARGET = editor
INCLUDEPATH += . include/ui

include(spec.pro)

# Input
HEADERS += include/editor.hpp \
           include/ui/MainWindow.hpp \
           include/ui/PokeEditWidget.hpp
SOURCES += src/main.cpp src/MainWindow.cpp src/PokeEditWidget.cpp
