######################################################################
# Automatically generated by qmake (3.0) lun. juin 15 14:01:40 2015
######################################################################

TEMPLATE = app
TARGET = editor
INCLUDEPATH += . include include/ui

include(spec.pro)

# Input
HEADERS += include/ui/PokeEditWindow.hpp \

SOURCES += src/main.cpp \
           src/PokeEditWindow.cpp \
